import type { Lesson } from '../types'

type StoryBeat = {
  arc: string
  episodeTitle: string
  location: string
  intro: string
  mission: string
  nextHook?: string
}

export type LessonStory = StoryBeat & {
  episodeNumber: number
}

const storyBeats: Record<string, StoryBeat> = {
  'self-introduction': {
    arc: '东京新生活',
    episodeTitle: '小田的第一句日语',
    location: '语言学校教室',
    intro: '小田第一天走进东京的语言学校，手心有点出汗。全班都在看新同学，他必须用最简单的日语把自己介绍出去。',
    mission: '用「～です」说出姓名、身份和基本信息，让别人知道“我是谁”。',
    nextHook: '刚坐下，旁边的田中就开始问他来自哪里。',
  },
  'where-are-you-from': {
    arc: '东京新生活',
    episodeTitle: '田中的第一问',
    location: '语言学校教室',
    intro: '田中对这个新来的中国同学很好奇。小田发现，自我介绍之后真正的聊天才刚开始。',
    mission: '用「～から来ました」说明自己来自哪里，并听懂别人问出身地。',
    nextHook: '田中越聊越快，小田终于听不清了。',
  },
  'please-speak-slowly': {
    arc: '东京新生活',
    episodeTitle: '请慢一点，别把我甩下',
    location: '教室课间',
    intro: '田中说得很热情，小田却只听见一串飞过去的音。他决定先学会一句能救命的请求。',
    mission: '礼貌请求对方说慢一点，用自然方式把谈话速度降下来。',
    nextHook: '第二天，小田正式来语言学校报到，却在门口犯了难。',
  },
  'language-school-registration': {
    arc: '东京新生活',
    episodeTitle: '报到日的小帮手',
    location: '语言学校受付',
    intro: '试听几天后，今天才是正式入学登记日。受付前排着队，小田捏着入学通知书正发愁——旁边一个爽朗的男生主动凑过来帮忙。',
    mission: '用「～はどこですか」找到受理处，完成登记并认识第一位不同班的朋友小师。',
    nextHook: '报到后的第二天清晨，小田在校门口遇见田中，被问起作业进度。',
  },
  'campus-greeting': {
    arc: '校园日常',
    episodeTitle: '早晨校门口的作业危机',
    location: '学校门口',
    intro: '报到后的第二天清晨，小田在校门口遇见田中，被问起昨天的作业。已经认识的小师路过，笑着说小田一大早就这么认真——作业危机变成了三个人的晨间小剧场。',
    mission: '用早晨问候、过去式和请求表达，完成一次自然的校园短聊。',
    nextHook: '进教室后，小田才发现自己忘带笔了。',
  },
  'borrow-pen-in-class': {
    arc: '校园日常',
    episodeTitle: '第一节课的借笔求生',
    location: '教室座位旁',
    intro: '老师已经开始板书，小田翻遍书包才发现笔不见了。小师把备用笔递过来，小田终于知道朋友也可以是课堂装备。',
    mission: '学会用「貸してください」借东西，并确认颜色、物品是否可以。',
    nextHook: '下课铃响，小田冲向便利店补早餐。',
  },
  'morning-combini-breakfast': {
    arc: '校园日常',
    episodeTitle: '饭团和加热按钮',
    location: '学校附近便利店',
    intro: '小田早上来不及吃饭，只能在便利店抓一个饭团。店员突然问要不要加热，小师又在旁边提醒他别空着肚子进教室。',
    mission: '完成便利店买早餐，听懂「温めますか」这类常见服务提问。',
    nextHook: '回到学校后，他又遇到一个不会操作的小麻烦。',
  },
  'how-to-do-it': {
    arc: '校园日常',
    episodeTitle: '复印机前的短暂停机',
    location: '学校走廊',
    intro: '老师让大家复印讲义，小田站在机器前研究半天，屏幕上的按钮看起来都很陌生。',
    mission: '用「どうやって」询问操作方法，并听懂步骤说明。',
    nextHook: '午休到了，食堂里几乎没有空座。',
  },
  'cafeteria-find-seat': {
    arc: '校园日常',
    episodeTitle: '食堂最后一个空位',
    location: '学校食堂',
    intro: '中午的食堂人声很满。小田端着餐盘，好不容易看到一个空位；小师在旁边提醒他，真正的第一步是礼貌开口。',
    mission: '用「～てもいいですか」询问许可，并自然回应别人让座。',
    nextHook: '吃完饭后，他在店里看到一个完全不认识的东西。',
  },
  'what-is-this': {
    arc: '城市探索',
    episodeTitle: '这是什么？小田的第一个店内发现',
    location: '学校附近小店',
    intro: '货架上摆着一个小田没见过的东西。小师说这是学校祭传单，小田决定把这次小发现贴进自己的日语笔记。',
    mission: '使用「これは何ですか」询问物品名称，并听懂简单解释。',
    nextHook: '下午放学后，小田第一次独自去车站。',
  },
  'asking-directions': {
    arc: '城市探索',
    episodeTitle: '车站到底在哪边',
    location: '学校外的路口',
    intro: '小田跟着导航绕了两圈，还是找不到车站入口。田中提醒他：迷路时先问人，不要和地图死磕。',
    mission: '用「～はどこですか」问地点，并听懂直走、左右转等方向词。',
    nextHook: '到了车站，更大的问题来了：这班车到底去不去池袋？',
  },
  'which-train-to-ikebukuro': {
    arc: '城市探索',
    episodeTitle: '站台上的池袋判断题',
    location: '电车站台',
    intro: '站台上电车一辆接一辆来，小田盯着线路图，越看越不确定。',
    mission: '确认电车是否去目的地，听懂「～に行きますか」。',
    nextHook: '确认方向之后，他还得学会怎么换乘。',
  },
  'train-transfer': {
    arc: '城市探索',
    episodeTitle: '新宿换乘挑战',
    location: '新宿站',
    intro: '新宿站像一个巨大的迷宫。小田跟着人流走了几步，决定先问清楚在哪里换乘。',
    mission: '询问换乘地点、线路和站台号，完成一次真实电车转乘。',
    nextHook: '转乘成功后，小田开始排队等餐。',
  },
  'n4_wait_how_long': {
    arc: '城市探索',
    episodeTitle: '队伍到底要等多久',
    location: '餐厅门口',
    intro: '热门餐厅门口排着长队，小田不想盲等，于是先问工作人员大概要多久。',
    mission: '用「どのくらい」询问等待时长，并听懂大约时间。',
    nextHook: '终于进店了，他要开始真正点午饭。',
  },
  'restaurant-order-lunch': {
    arc: '城市探索',
    episodeTitle: '今天推荐什么',
    location: '午餐定食店',
    intro: '菜单上字很多，小田看得有点晕。他决定先问推荐，让店员帮自己缩小选择。',
    mission: '询问推荐菜并用「それをお願いします」完成点餐。',
    nextHook: '下一次吃饭，小田遇到的是没有座位的问题。',
  },
  'restaurant-waiting-list': {
    arc: '城市探索',
    episodeTitle: '名字写在等位表上',
    location: '周末餐厅',
    intro: '田中带小田去一家人气餐厅，结果满座。小田第一次知道，日本餐厅还要先写名字等叫号。',
    mission: '听懂满座、写名字和等待时间的表达。',
    nextHook: '吃饭时，小田发现自己的拉面里可能会有芥末。',
  },
  'dont-put-wasabi': {
    arc: '城市探索',
    episodeTitle: '请不要放芥末',
    location: '餐厅柜台',
    intro: '小田对芥末还没准备好。他决定在点单时提前说清楚，避免一口下去表情失控。',
    mission: '用「入れないでください」表达“请不要放”。',
    nextHook: '吃完饭，结账时他开始关心价格。',
  },
  'how-much-is-it': {
    arc: '购物与付款',
    episodeTitle: '钱包打开之前先问价',
    location: '纪念品店',
    intro: '小田看中一个小礼物，但还没学会自然问价。他决定先把最实用的购物句拿下。',
    mission: '用「いくらですか」询问价格，并听懂金额。',
    nextHook: '真正付款时，他发现现金不太够。',
  },
  'pay-by-card': {
    arc: '购物与付款',
    episodeTitle: '现金不够，卡能不能救场',
    location: '收银台',
    intro: '小田摸了摸钱包，现金少得有点尴尬。他看见读卡器，决定问能不能刷卡。',
    mission: '确认付款方式，听懂刷卡、插卡、总金额。',
    nextHook: '为了以后不尴尬，他决定去 ATM 取点现金。',
  },
  'atm-withdraw-cash': {
    arc: '购物与付款',
    episodeTitle: 'ATM 前的手续费陷阱',
    location: '银行 ATM 区',
    intro: '小田第一次用日本 ATM，最担心按错按钮，更担心莫名其妙被收手续费。',
    mission: '询问取钱步骤和手续费，掌握 ATM 常见词。',
    nextHook: '手里有现金后，他终于可以买想要的手套了。',
  },
  'i-want-gloves': {
    arc: '购物与付款',
    episodeTitle: '冬天之前买手套',
    location: '服装店',
    intro: '东京的风比小田想象中冷。田中看见他骑车时冻红的手，建议他在冬天真正到来前买一副手套。',
    mission: '用「～が欲しいんですが」表达想买某物。',
    nextHook: '买完之后，他很快发现尺码并不合适。',
  },
  'exchange-size': {
    arc: '购物与付款',
    episodeTitle: '小票千万别丢',
    location: '服装店柜台',
    intro: '小田回家一试，尺码有点不合适。幸好小票还在，他回店里练习一次售后对话。',
    mission: '询问能否换尺码，并听懂小票、交换等售后关键词。',
    nextHook: '解决衣服后，他顺便去理个发。',
  },
  'hair-salon-cut': {
    arc: '购物与付款',
    episodeTitle: '不要剪太短',
    location: '理发店',
    intro: '小田坐上理发椅才意识到，最难的不是剪头发，而是准确说出“短一点，但不要太短”。小师在门口等他，准备第一时间评价新发型。',
    mission: '表达程度和限制，用「少し」「～すぎないでください」说明需求。',
    nextHook: '形象整理好了，小田和田中去附近神社逛逛。',
  },
  'do-you-have-omamori': {
    arc: '周末小旅行',
    episodeTitle: '想买一个护身符',
    location: '神社授与所',
    intro: '田中带小田去神社。小田想给家人带一个护身符，于是开始练习“有没有”。',
    mission: '用「～はありますか」询问是否有某物。',
    nextHook: '神社太好看了，小田想拍照。',
  },
  'can-i-take-a-photo': {
    arc: '周末小旅行',
    episodeTitle: '这里可以拍照吗',
    location: '神社庭院',
    intro: '小田举起手机前突然停住：这里能不能拍照？他决定先问清楚规则。',
    mission: '用「～てもいいですか」确认许可，避免失礼。',
    nextHook: '照片拍完，田中提议一起再去别的地方。',
  },
  'invite-photo': {
    arc: '朋友与约定',
    episodeTitle: '一起拍张照吧',
    location: '神社门口',
    intro: '小田想留下来日本后的第一张合照，但直接开口又有点不好意思。小师看穿了他的僵硬表情，开始现场指挥。',
    mission: '用「～ましょう」自然提出一起做某事。',
    nextHook: '合照之后，田中又发出了下一次邀请。',
  },
  'invite-go-together': {
    arc: '朋友与约定',
    episodeTitle: '要不要一起去',
    location: '放学路上',
    intro: '田中说周末有个展览，小田其实很想去，但需要学会更自然地发出邀请和回应。',
    mission: '用「～ませんか」提出邀请，并判断对方是否接受。',
    nextHook: '约好了要去，就必须把时间地点说清楚。',
  },
  'meet-at-what-time': {
    arc: '朋友与约定',
    episodeTitle: '明天几点见',
    location: '聊天窗口',
    intro: '小田和田中决定周末见面。现在最大的问题是：几点、在哪儿。',
    mission: '确认见面时间和地点，区分「に」和「で」。',
    nextHook: '第二天，小田还是遇到了电车晚点。',
  },
  'late-apology': {
    arc: '朋友与约定',
    episodeTitle: '迟到三分钟也要好好说',
    location: '车站前',
    intro: '电车晚点，小田一路小跑到车站。田中已经到了，他必须先道歉再解释。',
    mission: '用「遅れてすみません」道歉，并说明迟到原因。',
    nextHook: '周末结束后，小田开始认真利用学校图书馆。',
  },
  'library-books': {
    arc: '学习升级',
    episodeTitle: '书店里遇见小真',
    location: '图书馆与书店',
    intro: '小田先在图书馆借了一本日文读物，回去路上又走进附近的书店。书架前，小真正伸手去拿同一本书——像命运一样，两个人的故事从这一册开始了。',
    mission: '完成借书手续，并在书店偶遇里用「好きです」「読むことが好きです」聊出共同兴趣，别急着结束对话。',
    nextHook: '小田还想告诉小真：这本他其实读过类似的中文版。',
  },
  'i-have-read-it': {
    arc: '学习升级',
    episodeTitle: '这本我读过',
    location: '图书馆阅读区',
    intro: '田中推荐一本书，小田突然发现自己以前读过类似主题。表达经验的句型派上用场了。',
    mission: '用「～たことがあります」表达曾经做过某事。',
    nextHook: '读书时遇到一个文化点，小田想解释自己为什么惊讶。',
  },
  'n4_reason_because_first_time': {
    arc: '学习升级',
    episodeTitle: '第一次所以会紧张',
    location: '图书馆走廊',
    intro: '小田回想刚到日本的第一周，很多反应其实都来自“第一次”。他学会把原因说出来。',
    mission: '用「～だったから」说明理由。',
    nextHook: '接下来，他和田中开始比较室内室外去哪儿更好。',
  },
  'n4_compare_outside_better': {
    arc: '学习升级',
    episodeTitle: '外面还是里面',
    location: '学校门口',
    intro: '天气不错但风有点大，小田和田中站在门口讨论去哪儿。比较表达终于有了用处。',
    mission: '用「Aのほうがいい」表达偏好。',
    nextHook: '天空突然变暗，计划又要改变。',
  },
  'weather-plan-change': {
    arc: '学习升级',
    episodeTitle: '雨云来了，计划改了',
    location: '街角',
    intro: '原本想去外面走走，但天空变得很暗。小田第一次用日语提出改变计划。',
    mission: '用「～そうです」观察天气，并用比较句改计划。',
    nextHook: '周末旅行开始，小田要先确认浴场时间。',
  },
  'what-time-is-the-bath': {
    arc: '周末旅行',
    episodeTitle: '温泉几点开到几点',
    location: '旅馆前台',
    intro: '小田第一次住日式旅馆，最关心的是浴场时间。小张提前发来生活警告：错过浴场时间，旅行体验会直接掉血。',
    mission: '用「何時から何時まで」询问开放时间。',
    nextHook: '入住时，前台开始要求护照和预约信息。',
  },
  'hotel-check-in': {
    arc: '周末旅行',
    episodeTitle: '我有预约',
    location: '酒店前台',
    intro: '旅行真正开始了。小田站在前台，努力把预约、姓名和护照一步步说清楚。',
    mission: '完成酒店入住，听懂证件和楼层信息。',
    nextHook: '旅行回来后，生活琐事开始排队出现。',
  },
  'laundry-machine-how-to-use': {
    arc: '独立生活',
    episodeTitle: '洗衣机也像考试题',
    location: '公寓洗衣房',
    intro: '小田第一次使用公寓公共洗衣机，按钮和说明都很陌生。室友小张一边吐槽泡沫危机，一边把生活经验塞给他。',
    mission: '询问机器用法，听懂首先、接着等步骤说明。',
    nextHook: '洗完衣服，他又遇到日本生活的另一关：垃圾分类。',
  },
  'garbage-sorting': {
    arc: '独立生活',
    episodeTitle: '垃圾不是想扔就扔',
    location: '公寓垃圾站',
    intro: '小田拎着垃圾袋走到楼下，被分类规则拦住了。小张说，日本垃圾分类不是规则，是每周固定刷新的生活副本。',
    mission: '确认垃圾分类、丢垃圾日期和时间。',
    nextHook: '整理房间时，他发现有东西要寄回中国。',
  },
  'post-office-package': {
    arc: '独立生活',
    episodeTitle: '把小礼物寄回家',
    location: '邮局窗口',
    intro: '小田想把在日本买的小礼物寄给家人，也想给小真寄一点东京的日常。邮局职员开始问航空还是海运。',
    mission: '说明寄送目的地、选择寄送方式，并听懂费用。',
    nextHook: '与此同时，小田自己也错过了一次快递。',
  },
  'delivery-redelivery': {
    arc: '独立生活',
    episodeTitle: '错过快递后的电话挑战',
    location: '公寓房间',
    intro: '门口留着一张不在票。小田深吸一口气，第一次用日语电话预约再配送。',
    mission: '用电话预约再配送，并确认时间段。',
    nextHook: '生活继续，小田发现现金又不够了。',
  },
  'throat-hurts': {
    arc: '健康与突发',
    episodeTitle: '嗓子开始抗议',
    location: '教室课间',
    intro: '连着几天奔波后，小田嗓子有点疼。田中提醒他要说清楚症状。',
    mission: '用「のどが痛いんです」说明身体不适。',
    nextHook: '症状没有马上好，小田决定去药店。',
  },
  'pharmacy-cold-medicine': {
    arc: '健康与突发',
    episodeTitle: '一天三次的药',
    location: '药店',
    intro: '小田走进药店，第一次自己描述症状并听店员说明用药次数。',
    mission: '购买感冒药，听懂症状和服药频率。',
    nextHook: '如果还没好，他可能要去医院挂号。',
  },
  'clinic-reception': {
    arc: '健康与突发',
    episodeTitle: '保险证带了吗',
    location: '医院前台',
    intro: '发烧还没退，小田来到医院。前台的问题不难，但每一句都关系到能不能顺利看诊。',
    mission: '说明症状开始时间，并回答是否带保险证。',
    nextHook: '身体好了，可钱包却在外出时不见了。',
  },
  'lost-wallet': {
    arc: '健康与突发',
    episodeTitle: '钱包不见了',
    location: '车站服务台',
    intro: '小田摸口袋时心里一空：钱包不见了。小张的现实主义提醒突然派上用场：先深呼吸，再找车站员。',
    mission: '用「～てしまいました」表达不小心发生的遗憾事件。',
    nextHook: '因为身体和钱包的麻烦，小田还得写一份请假说明。',
  },
  'absence-note': {
    arc: '健康与突发',
    episodeTitle: '给老师的请假说明',
    location: '给老师的消息',
    intro: '小田不想只发一句“我不去了”。他练习用更正式的表达把原因和请求写清楚。',
    mission: '用「～のため」「休ませてください」完成礼貌请假。',
    nextHook: '恢复之后，朋友又发来邀请，但小田那天已经有事。',
  },
  'refuse-invitation': {
    arc: '更自然的交际',
    episodeTitle: '想去，但这次真的不行',
    location: '聊天窗口',
    intro: '田中邀请小田看电影。小田其实想去，但已经有安排，只能练习一次不伤人的拒绝。',
    mission: '用「～たいんですが、ちょっと…」委婉拒绝邀请。',
    nextHook: '更自然的交际之后，小田开始听懂传闻和计划。',
  },
  'n3_hearsay_concert': {
    arc: '更自然的交际',
    episodeTitle: '听说有演唱会',
    location: '学校公告栏前',
    intro: '同学们围在公告栏前讨论周末活动。小田听见“そうです”，开始区分听说和看起来。',
    mission: '用「～そうです」表达听说的信息。',
    nextHook: '知道消息后，小田开始计划送礼物。',
  },
  'n3_plan_intend_to_give': {
    arc: '更自然的交际',
    episodeTitle: '生日礼物作战',
    location: '商店街',
    intro: '田中的生日快到了。小田想准备礼物，却要先把自己的打算说清楚。',
    mission: '用「～つもりです」表达计划和意图。',
    nextHook: '生活稳定后，小田决定尝试找一份兼职。',
  },
  'part-time-interview': {
    arc: '更自然的交际',
    episodeTitle: '第一次打工面试',
    location: '咖啡店后台',
    intro: '小田走进咖啡店面试，店长直接问一周能上几次班。小张说面试靠声量，小真说小田可以，这已经不是课本日语，而是真生活。',
    mission: '说明自己能工作的日期和时间，听懂面试里的排班表达。',
    nextHook: '兼职开始前，他还要学会更正式地请求别人检查日语。',
  },
  'n2_polite_request_check_japanese': {
    arc: '更自然的交际',
    episodeTitle: '请帮我检查这句日语',
    location: '学校自习室',
    intro: '小田写好打工申请消息，但总觉得哪里不自然。他请老师帮忙检查，开始进入更正式的表达。',
    mission: '用更礼貌的「チェックしてもらえませんか」请求帮助。',
  },
}

const defaultStory: StoryBeat = {
  arc: '小田的日本生活',
  episodeTitle: '今天也要把一句话说出去',
  location: '东京',
  intro: '小田继续在日本生活里练习日语。每一课都不是孤立句型，而是他必须亲自开口解决的小事件。',
  mission: '读懂背景，听懂对话，并把本课句型用在真实场景里。',
}

const speakerNames: Record<string, string> = {
  '你': '小田',
  '李': '小田',
  '友達': '田中',
  '朋友': '田中',
  '同学': '田中',
  '学生': '旁边同学',
  '田中': '田中',
  '小真': '小真',
  '小真（扎发）': '小真',
  '小师': '小师',
  '小张': '小张',
  '老师': '山本老师',
  '先生': '山本老师',
  '店员': '店员佐藤',
  '路人': '路过的上班族',
  '駅员': '车站员',
  '工作人员': '工作人员',
  '职员': '邮局职员',
  '客服': '配送客服',
  '邻居': '邻居高桥',
  '前台': '前台',
  '理发师': '理发师',
  '店长': '店长',
}

export function getLessonStory(lesson: Lesson, unitIndex = 0): LessonStory {
  const beat = storyBeats[lesson.id] ?? defaultStory
  return {
    ...beat,
    episodeNumber: unitIndex,
  }
}

export function getStorySpeakerName(rawSpeaker: string): string {
  return speakerNames[rawSpeaker] ?? rawSpeaker
}
